#version 450 core

/* These are built-in variables for use in compute shaders.
in uvec3 gl_NumWorkGroups;
in uvec3 gl_WorkGroupID;
in uvec3 gl_LocalInvocationID;
in uvec3 gl_GlobalInvocationID;
in uint  gl_LocalInvocationIndex;
*/

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outputImage; 

void main() {
    vec4 outputColor = vec4((gl_GlobalInvocationID.x & 0xF) / 15.0, (gl_GlobalInvocationID.y & 0xF) / 15.0, 0.0, 0.0);
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), outputColor);
}
