#ifndef RENDERTHREAD_TASKS_RENDERTASKS_INCLUDED
#define RENDERTHREAD_TASKS_RENDERTASKS_INCLUDED

#include "RenderTaskBase.h"
#include "RenderTaskControl.h"

#endif // RENDERTHREAD_TASKS_RENDERTASKS_INCLUDED
