#ifndef MEMORY_SHADERPARAMETERS_SHADERPARAMETERVALUE_INCLUDED
#define MEMORY_SHADERPARAMETERS_SHADERPARAMETERVALUE_INCLUDED

namespace Engine {
    namespace ShdrRfl {
        class ShaderParameters {

        };
    }
}

#endif // MEMORY_SHADERPARAMETERS_SHADERPARAMETERVALUE_INCLUDED
