#ifndef RENDER_ENUMS_SAMPLERSTATES_INCLUDED
#define RENDER_ENUMS_SAMPLERSTATES_INCLUDED

#include "enum_factory.h"
#include <cstdint>

#define ADDRESS_MODE_ENUM_DEF(XMACRO) \
    XMACRO(AddressMode, Repeat) \
    XMACRO(AddressMode, MirroredRepeat) \
    XMACRO(AddressMode, ClampToEdge) \


#define FILTER_MODE_ENUM_DEF(XMACRO) \
    XMACRO(FilterMode, Point) \
    XMACRO(FilterMode, Linear) \


DECLARE_ENUM_WITH_UTYPE(AddressMode, uint8_t, ADDRESS_MODE_ENUM_DEF)
DECLARE_REFLECTIVE_FUNCTIONS(AddressMode, ADDRESS_MODE_ENUM_DEF)
DECLARE_ENUM_WITH_UTYPE(FilterMode, uint8_t, FILTER_MODE_ENUM_DEF)
DECLARE_REFLECTIVE_FUNCTIONS(FilterMode, FILTER_MODE_ENUM_DEF)

#endif // RENDER_ENUMS_SAMPLERSTATES_INCLUDED
