#ifndef RENDER_ENUMS_SAMPLERSTATES_INCLUDED
#define RENDER_ENUMS_SAMPLERSTATES_INCLUDED

#include "enum_factory.h"
#include <cstdint>

#define SAMPLER_ADDRESS_MODE_ENUM_DEF(XMACRO) \
    XMACRO(SamplerAddressMode, Repeat) \
    XMACRO(SamplerAddressMode, MirroredRepeat) \
    XMACRO(SamplerAddressMode, ClampToEdge) \


#define SAMPLER_FILTER_MODE_ENUM_DEF(XMACRO) \
    XMACRO(SamplerFilterMode, Point) \
    XMACRO(SamplerFilterMode, Linear) \


DECLARE_ENUM_WITH_UTYPE(SamplerAddressMode, uint8_t, SAMPLER_ADDRESS_MODE_ENUM_DEF)
DECLARE_REFLECTIVE_FUNCTIONS(SamplerAddressMode, SAMPLER_ADDRESS_MODE_ENUM_DEF)
DECLARE_ENUM_WITH_UTYPE(SamplerFilterMode, uint8_t, SAMPLER_FILTER_MODE_ENUM_DEF)
DECLARE_REFLECTIVE_FUNCTIONS(SamplerFilterMode, SAMPLER_FILTER_MODE_ENUM_DEF)

#endif // RENDER_ENUMS_SAMPLERSTATES_INCLUDED
